### ISSUE TITLE
build issue with glfw

### ISSUE THREAD

**Issue by hoppss** [MRPT/mrpt#1065]
error prompt as following,

```
[ 60%] Linking CXX executable ../../bin/robotic-arm-kinematics
/usr/bin/ld: //usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

I have installed libglfw3-dev, could you help me solve this problem?
```bash
 sudo apt-get install libglfw3-dev 
sudo apt-get install libx11-dev  
```

**Comment by jlblancoc** [comment]
It seems the problem is a conflict between the system library (the one installed via apt) and another version you have under "/usr/**local**/..."... 

I strongly recommend NOT installing anything under /usr/local, it was common in the past (20+ years ago? :-) ), but can only lead to problems like this... nowadays, with apt, and local cmake builds (without doing a "make install"), things are far safer...

You should remove everything under /usr/local, unless you know why those files are there and you really need them...

**Comment by hoppss** [comment]
Thanks
