### ISSUE TITLE
`rangeImage` wrong format?

### ISSUE THREAD

**Issue by christian-rauch** [MRPT/mrpt#1178]
In `1.5.8`, the `CObservation::rangeImage` had type `CMatrix` with units metre ("a matrix of floats with the range data as captured by the camera (in meters)"). In 2.x, this changed to type `CMatrix_u16`, suggesting that distances are stores as 16bit millimetre, but the documentation still says "a matrix of floats with the range data as captured by the camera (in meters)".

There are two issues here:
1. the documentation is confusing about the stored unit (metre, millimetre)
2. changing the unit to millimetre silently breaks many algorithms that read that data and assume it is stored in metres as before

**Comment by jlblancoc** [comment]
Thanks for raising the issue, @christian-rauch ! 

> 1. the documentation is confusing about the stored unit (metre, millimetre)

It's been fixed in 037863b91598150c482759d2ee2be721f27560b5, within hours it will be reflected [on the online docs](https://docs.mrpt.org/reference/latest/class_mrpt_obs_CObservation3DRangeScan.html). Let me know if you still see inconsistencies... maintaining the docs is a huge and endless effort! ;-)

> 2. changing the unit to millimetre silently breaks many algorithms that read that data and assume it is stored in metres as before

Sorry for that, here we should have changed the name to break builds after the change, you are right.
The change to uint16_t was strongly motivated, though: 
- More memory efficient (50% storage / memory cost), 
- Possibility of faster processing via SIMD instructions.
- Faster comparison on the CPU w/o involving the FPU.
