### ISSUE TITLE
No C++ support for std::filesystem

### ISSUE THREAD

**Issue by yurivict** [MRPT/mrpt#1210]
```
CMake Error at cmakemodules/FindFilesystem.cmake:73 (message):
  No C++ support for std::filesystem
Call Stack (most recent call first):
  libs/system/CMakeLists.txt:4 (find_package)
```

```std::filesystem``` is supported by the compiler.

It is looking for libstdc++fs, but on FreeBSD the library name is libc++.

clang-12
OS: FreeBSD 13

**Comment by jlblancoc** [comment]
@yurivict Thanks! It's fixed now in #1212 

Note however that further build errors are found by the actual compilation: mrpt-core cannot be built due to clang not finding basic headers like `<string>`. I tried playing with `-stdlib=xxx` without luck... Any help on this and/or PRs would be appreciated!
