### ISSUE TITLE
Source packages release do not contain submodules

### ISSUE THREAD

**Issue by roncapat** [MRPT/mrpt#1274]
When building from source archives (not using git clone) the build fails with:
```
CMake Error at CMakeLists.txt:50 (message):
  git submodules missing! You probably did not clone the project with
  --recursive.  It is possible to recover by calling:

    git submodule update --init --recursive
```

but of course this can't be done since the distributed archive is not a git repository.

**Comment by jlblancoc** [comment]
Hi @roncapat 

Yes, that's a limitation of the automatic github source archives in releases. That's why we also provide alternative TGZs / ZIPs with the whole thing (incl. submodules), they are here: 

![Screenshot from 2023-06-15 11-25-31](https://github.com/MRPT/mrpt/assets/5497818/bfbf9494-fa25-4a1f-ba9e-caa310f85e5f)

If those don't contain the submodules then it's a real bug...
