### ISSUE TITLE
CMultiMetricMapPDF::rebuildAverageMap() SSE2 on Linux

### ISSUE THREAD

**Issue by jolting** [MRPT/mrpt#248]
`checkSuportSSE()` returns false, so is this dead code?
https://github.com/MRPT/mrpt/blob/master/libs/slam/src/slam/CMultiMetricMapPDF.cpp#L52
https://github.com/MRPT/mrpt/blob/master/libs/slam/src/slam/CMultiMetricMapPDF.cpp#L377

Also looks like you're missing a p in Support.

Could this code run on 64-bit Linux by changing unsigned short to uint16_t?

**Comment by jlblancoc** [comment]
Yes, it is dead code, thanks for spotting that ugly zone!!

It comes from tests for a research paper back in ~2009.
I'll give it a look before 1.5.0, to remember whether it's commented out because there was something fundamentally wrong in doing that computation with SSE, or it was just a quick desperate solution to build errors in some platform... :-S

PS: checkSuportSSE() should be removed anyway and just rely on CMake-defined flags.
