### ISSUE TITLE
how to convert CColouredPointsMap to CSimplePointsMap

### ISSUE THREAD

**Issue by hubing1994** [MRPT/mrpt#256]
i am using the rrt module.And my obstacle pointcloud is CColouredPointsMap type,however the obstacle pointcloud of rrt module is CSimplePointsMap. I use the sub fucntion named "getAsSimplePointsMap",but it does not work, the program is always crashed.the code is showed as belows:
    mrpt::maps::CSimplePointsMap obstacle;
    obstacle = *mrpt_curve_pointcloud.getAsSimplePointsMap();
 planner_input_temp.obstacles_points.insertAnotherMap(&obstacle,mrpt::poses::CPose3D(0,0,0,my_pi/2,0,0));

**Comment by jlblancoc** [comment]
Hi, 

if you see the docs for `getAsSimplePointsMap()`, it says that it will return NULL if the map is not already a `CSimplePointsMap`, hence the crash due to dereferencing NULL.

You could use this other function and it should work: 

`obstacle.insertAnotherMap( &mrpt_curve_pointcloud, mrpt::poses::CPose3D() );`
