### ISSUE TITLE
How to convert my graph to a ".simplemap" file?

### ISSUE THREAD

**Issue by buki26** [MRPT/mrpt#379]
I am a new user of mrpt library and I met a problem while using "map-partition". There is a ready-to-use application and I can run it with a “.simplemap” file passed in the command line. But how can I use this function with my graph? How can I convert my graph to a ".simplemap" file? Thank you very much to read and answer my question.

**Comment by bergercookie** [comment]
Hi @buki26,

The map-partition application utilises the [CIncrementalMapPartitioner class](https://github.com/MRPT/mrpt/blob/master/libs/slam/include/mrpt/slam/CIncrementalMapPartitioner.h) so you could just use this library in your application. 

This is a rather general answer since I haven't exactly understood your question though. What's your graph used for? Is it a graph of SLAM poses - i.e. graphsLAM? If so, you could take a look at the [CloopCloserERD](https://github.com/MRPT/mrpt/blob/master/libs/graphslam/include/mrpt/graphslam/ERD/CLoopCloserERD.h) class of the mrpt-graphslam lib that uses this class to do exactly that, partition the measurements and based on that split them into groups.
