### ISSUE TITLE
camera-calibration-checker-board_9x7.pdf not quadratic

### ISSUE THREAD

**Issue by tik0** [MRPT/mrpt#562]
I just like to mention that the camera-calibration-checker-board_9x7.pdf you provide [here](http://www.mrpt.org/downloads/camera-calibration-checker-board_9x7.pdf) consists out of non-quadratics.
The single patterns (measured with inkscape) are somehow 22.5 mm x 24.5 mm.
Is this on purpose?
And if so, what is the deal with it?

**Comment by jlblancoc** [comment]
Hi, and thanks for pointing it out!

Actually, I can't remember :-) But surely it was not on purpose. The web page doesn't mention the exact length of the quads because unintentional scaling while printing may change their size. 

Anyhow: MRPT's [camera-calib](http://www.mrpt.org/list-of-mrpt-apps/application_camera-calib/) has an entry for both, X and Y sizes in mm, so in practice there is no big deal with quads being rectangles... 

![screenshot from 2017-07-18 01-40-58](https://user-images.githubusercontent.com/5497818/28294444-9456382e-6b5a-11e7-9104-387a129a9aec.png)

Hope it helps!
