### ISSUE TITLE
Dead link on web site?

### ISSUE THREAD

**Issue by rebcabin** [MRPT/mrpt#881]
The index page of the site advertises this URL:

    https://www.mrpt.org/The_MRPT_book

but I get a 404

**Comment by jolting** [comment]
It is here: 
https://www.mrpt.org/tutorials/the-mrpt-book/

Unfortunately, that book has not been updated since 2010. The first chapter states MRPT is GPL 3 licensed. That's wrong. MRPT 2.0 also had some namespace changes, which probably lead to some new inaccuracies.

Perhaps it can be a topic for Google Season of Docs. More on that in January.

@jlblancoc Thoughts?

**Comment by jlblancoc** [comment]
Thanks @rebcabin !

I guess you meant the main page of the Doxygen docs, right? I just updated a bit that (quite old!) page: 5bd8230b4fc31018e8d81aa8a15d1e10c3752a85

@jolting Yep! Improving the docs would be a great GSoC task... we already have this ticket open #805  , we could elaborate on it a bit more and let it be a project proposal.

**Comment by jlblancoc** [comment]
The doc is now rebuilt online... there was also a small bug ([fixed](https://github.com/jlblancoc/git2docs/commit/a8285c48fa4517c5704cc61f028a4ac541a0888b)) that has been preventing the docs to regenerate during the last days.
