### ISSUE TITLE
Visualising depths in rawlog

### ISSUE THREAD

**Issue by hoonkai** [MRPT/mrpt#958]
Hi

I wonder if there's any tool available for visualising depths in a rawlog file as depth images. I have converted the TUM dataset RGBD images to a rawlog file using the rgbd_dataset2rawlog tool, but I'd like to verify that the depths are preserved. Is there a tool for that?

Thanks

**Comment by jolting** [comment]
Did you try the RawLogViewer?

**Comment by hoonkai** [comment]
> Did you try the RawLogViewer?

Yes, I can see point clouds but not depth images.

**Comment by jolting** [comment]
I could be wrong, but I don't think that feature exists yet. I think it would be a great feature request for RawLogViewer.

Take a look here for examples on how to add it:
https://github.com/MRPT/mrpt/blob/1de0e027c16e094e1fe6e5327731db5148ba8bbe/apps/kinect-3d-view/kinect-3d-view_main.cpp#L217
https://github.com/MRPT/mrpt/blob/1de0e027c16e094e1fe6e5327731db5148ba8bbe/apps/kinect-3d-view/kinect-3d-view_main.cpp#L264

**Comment by hoonkai** [comment]
Right. Thanks for that.

**Comment by jlblancoc** [comment]
Hmm... Do you mean a visualization of the depth image/matrix? It has been already there in RawLogViewer for ages! :-) You must just select the "range" tab, to see the range instead of the pointcloud. I'm assuming you have `CObservation3DRangeScan` objects, right?

See the attached screenshot:

![Screenshot from 2019-09-18 22-18-42](https://user-images.githubusercontent.com/5497818/65182852-871d3800-da62-11e9-982f-8869e4bd83ce.png)

You can right click on the image to save it to disk, or use the tool `rawlog-edit` to ensure that range images are already all saved as external files, if that's needed.

**Comment by hoonkai** [comment]
> Hmm... Do you mean a visualization of the depth image/matrix? It has been already there in RawLogViewer for ages! :-) You must just select the "range" tab, to see the range instead of the pointcloud. I'm assuming you have `CObservation3DRangeScan` objects, right?
> 
> See the attached screenshot:
> 
> ![Screenshot from 2019-09-18 22-18-42](https://user-images.githubusercontent.com/5497818/65182852-871d3800-da62-11e9-982f-8869e4bd83ce.png)
> 
> You can right click on the image to save it to disk, or use the tool `rawlog-edit` to ensure that range images are already all saved as external files, if that's needed.

You're right! Thanks so much.
